; Readable NASM reference for the stage-1 loader generated by create_iso.py.
; The Python builder is canonical because it derives KERNEL_SECTORS from the
; generated kernel and verifies the complete artifact set.

BITS 16
ORG 0x7C00

%ifndef KERNEL_SECTORS
%define KERNEL_SECTORS 3
%endif

start:
    cli
    xor ax, ax
    mov ds, ax
    mov es, ax
    mov ss, ax
    mov sp, 0x7C00
    sti
    cld

    mov [boot_drive], dl
    mov dx, 0x00E9
    mov al, 'B'
    out dx, al

    mov si, 3
.disk_retry:
    mov dl, [boot_drive]
    xor ax, ax
    int 0x13

    xor ax, ax
    mov es, ax
    mov bx, 0x1000
    mov ax, 0x0200 + KERNEL_SECTORS
    mov cx, 0x0002
    mov dh, 0
    mov dl, [boot_drive]
    int 0x13
    jnc .loaded
    dec si
    jnz .disk_retry

    mov si, disk_error_msg
    call print_string
.disk_error:
    cli
    hlt
    jmp .disk_error

.loaded:
    jmp 0x0000:0x1000

print_string:
    mov bx, 0x0007
.print_loop:
    lodsb
    cmp al, 0
    je .print_done
    mov ah, 0x0E
    int 0x10
    jmp .print_loop
.print_done:
    ret

boot_drive db 0
disk_error_msg db 0x0D, 0x0A, 'Envo disk read failed', 0x0D, 0x0A, 0

times 510-($-$$) db 0
dw 0xAA55
